version: '3'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
    networks:
      - rag-network

volumes:
  qdrant_data:

networks:
  rag-network:
    driver: bridge